version: "3.7"

services:
  web:
    image: webdevops/php-apache:alpine-php7
    ports:
      - "4500:80"
    volumes:
      - ./www:/app

    networks:
      - minha-rede

  db:
    image: mysql:5.7
    environment:
      
      MYSQL_DATABASE: "site"
      MYSQL_USER: "site_adm"
      MYSQL_PASSWORD: "adm_site"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

    networks:
      - minha-rede

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    
      
    ports:
      - "8080:80"
    

    networks:
      - minha-rede

networks:
   minha-rede:
     driver: bridge

